blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/yourusername/LinkPreview/discussions
    about: Ask questions or discuss ideas with the community
  - name: Security Issue
    url: https://github.com/yourusername/LinkPreview/security/advisories/new
    about: Report a security vulnerability (private)
